# config/config.yaml - Main configuration file
model_id: "meta-llama/Llama-3.3-70B-Instruct"
use_quantization: true
max_new_tokens: 800
temperature: 0.3
input_dir: "data/input"
output_dir: "data/output"
default_num_topics: 10
file_encoding: "utf-8"

---

# config/prompts/webcam_prompts.yaml - Your webcam-specific prompts
prompts:
  - name: "webcam_experience_detailed"
    description: "Detailed analysis of webcam experience interviews"
    template: |
      You are analyzing interview transcripts where participants were asked to share their experiences using five webcam setups: [insta], [single iphone], [dual iphones], [logitech], and [obsbot].

      The transcripts are organized in the following format:
      Each section begins with the webcam label (e.g., "### insta") followed by participant comments about that device.
      Ignore filler words, repeated question prompts, or interviewer language. Focus only on participant speech that offers insight, reaction, or description.

      Your task is to identify **exactly {num_topics} meaningful and distinctive words or short phrases** that summarize participants' real experiences for **each webcam setup**.

      Guidelines:
      - Do NOT just pick the most frequent words.
      - Select words or short phrases that are **emotionally descriptive**, **technically relevant**, or **highlight distinctive qualities** (positive or negative).
      - Avoid: generic words (e.g., "thing", "camera"), filler words, or phrases repeated from the question.

      For each setup, return a bullet list of {num_topics} high-quality descriptors.

      Output format:
      ### [setup]
      - ...
      - ...
      - ...

      Content to analyze:
      {content}
    default_num_topics: 10
    system_message: "You are an expert at analyzing interview transcripts and extracting meaningful participant experiences."
    tags: ["webcam", "interviews", "experience", "qualitative"]

  - name: "webcam_sentiment"
    description: "Extract sentiment-focused topics from webcam experiences"
    template: |
      Analyze the following webcam experience transcript and identify the {num_topics} most important emotional or sentiment-related topics.

      Focus on:
      - Emotional reactions (positive, negative, neutral)
      - Comfort levels and usability feelings
      - Aesthetic preferences and visual impressions
      - Behavioral changes or adaptations

      Return {num_topics} sentiment-focused topics as bullet points.

      Content to analyze:
      {content}
    default_num_topics: 8
    tags: ["sentiment", "emotion", "user experience"]

---

# config/prompts/general_prompts.yaml - General-purpose prompts
prompts:
  - name: "document_themes"
    description: "Extract main themes from document collections"
    template: |
      Analyze the following documents and identify the {num_topics} most important themes that appear across the content.

      Focus on:
      - Central ideas and concepts
      - Recurring patterns or subjects
      - Key discussion points
      - Important categories or topics

      Return exactly {num_topics} themes as a numbered list.

      Documents to analyze:
      {content}
    default_num_topics: 10
    tags: ["themes", "general", "analysis"]

  - name: "keyword_extraction"
    description: "Extract important keywords and phrases"
    template: |
      Extract the {num_topics} most important keywords or short phrases from the following content.

      Guidelines:
      - Focus on substantive, meaningful terms
      - Avoid common stop words and filler
      - Include both single words and short phrases (2-3 words)
      - Prioritize terms that capture key concepts

      Return {num_topics} keywords as bullet points.

      Content:
      {content}
    default_num_topics: 15
    tags: ["keywords", "extraction", "nlp"]

---

# Alternative: config/prompts/your_webcam_prompt.txt - Simple text file version
You are analyzing interview transcripts where participants were asked to share their experiences using five webcam setups: [insta], [single iphone], [dual iphones], [logitech], and [obsbot].

The transcripts are organized in the following format:
Each section begins with the webcam label (e.g., "### insta") followed by participant comments about that device.
Ignore filler words, repeated question prompts, or interviewer language. Focus only on participant speech that offers insight, reaction, or description.

Your task is to identify **exactly {num_topics} meaningful and distinctive words or short phrases** that summarize participants' real experiences for **each webcam setup**.

Guidelines:
- Do NOT just pick the most frequent words.
- Select words or short phrases that are **emotionally descriptive**, **technically relevant**, or **highlight distinctive qualities** (positive or negative).
- Avoid: generic words (e.g., "thing", "camera"), filler words, or phrases repeated from the question.

For each setup, return a bullet list of {num_topics} high-quality descriptors.

Output format:
### [setup]
- ...
- ...
- ...
- ...

Content to analyze:
{content}